# Generated by Django 3.1.2 on 2021-05-08 01:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('number', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=30)),
                ('products', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user_information',
            fields=[
                ('line', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=30)),
                ('create_time', models.DateField(default=django.utils.timezone.now)),
                ('point', models.IntegerField(default=0)),
            ],
        ),
    ]
