# Generated by Django 3.1.2 on 2021-05-08 13:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pui', '0003_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopping_cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('buy_product', models.TextField()),
                ('buy_quantity', models.TextField()),
                ('total_price', models.IntegerField()),
                ('buy_time', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
