# Generated by Django 3.1.2 on 2021-05-08 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pui', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='products',
        ),
    ]
