# Generated by Django 3.1.2 on 2021-05-09 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pui', '0004_shopping_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_information',
        ),
    ]
