# Generated by Django 3.1.2 on 2021-05-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pui', '0005_delete_user_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopping_cart2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('buy_product', models.TextField()),
                ('buy_quantity', models.TextField()),
                ('total_price', models.IntegerField()),
                ('buy_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
