# Generated by Django 3.1.2 on 2021-05-09 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pui', '0006_shopping_cart2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='shopping_cart',
        ),
    ]
